/**
 * Learn domain layer (COMP-015, COMP-016, COMP-017, COMP-018).
 */

export {
  IL1ViolationError,
  InvalidMentorshipTransitionError,
  InvalidPhaseTransitionError,
  LearnDomainError,
  MentorCapacityExceededError,
  NotMentorError,
  NotReviewerError,
} from "./errors.js";
export {
  CodeArtifact,
  Fragment,
  FragmentReviewService,
  FragmentSection,
  FragmentStatus,
  ProgressTrackingService,
  QuizArtifact,
  TextArtifact,
  VideoArtifact,
  type FragmentParams,
  type FragmentReviewServiceParams,
  type FragmentSectionParams,
  type FragmentSectionType,
  type ProgressTrackingServiceParams,
} from "./fragment-artifact/index.js";
export {
  Career,
  Course,
  CourseStatus,
  FogOfWarNavigationService,
  PrerequisiteEvaluator,
  Track,
  type AccessibleContentResult,
  type CareerParams,
  type CourseParams,
  type LockedCourse,
  type PrerequisiteEvaluationResult,
  type TrackParams,
  type UnlockedCourse,
} from "./content-hierarchy/index.js";
export {
  AIGeneratedDraft,
  CreatorWorkflow,
  CREATOR_WORKFLOW_PHASES,
  getNextPhase,
  isValidNextPhase,
  isCreatorWorkflowPhase,
  type AIGeneratedDraftParams,
  type CreatorWorkflowParams,
  type CreatorWorkflowPhase,
  type CreatorWorkflowDomainEvent,
  type CreatorWorkflowPhaseEntered,
} from "./creator-tools/index.js";
export {
  MAX_ACTIVE_MENTORSHIPS_PER_MENTOR,
  MentorReview,
  MentorshipRelationship,
  InvalidReviewRatingError,
  RelationshipNotConcludedError,
  ReviewerMustBeMentorError,
  canAccept,
  canConclude,
  canDecline,
  isMentorshipStatus,
  MENTORSHIP_STATUSES,
  type MentorReviewParams,
  type MentorshipRelationshipParams,
  type MentorshipStatus,
  type ArtifactGallery,
  type ArtifactGalleryItem,
  type MentorshipRepositoryPort,
  type MentorshipConcluded,
  type MentorshipDeclined,
  type MentorshipDomainEvent,
  type MentorshipProposed,
  type MentorshipStarted,
} from "./mentorship/index.js";
