export {
  Artifact,
  ArtifactStatus,
  createArtifactId,
  createAuthorId,
  createContentHash,
  createNostrEventId,
  InvalidLifecycleTransitionError,
  isArtifactId,
  isArtifactStatus,
  isAuthorId,
  isContentHash,
  isNostrEventId,
} from "./artifact-registry/index.js";
export type {
  ArtifactId,
  AuthorId,
  ContentHash,
  NostrEventId,
  NostrRelayPort,
  AnchoringPayload,
  ArtifactRepository,
  ArtifactLifecycleEventPublisher,
  ArtifactLifecycleEvent,
  ArtifactDraftedEvent,
  ArtifactSubmittedEvent,
  ArtifactPublishedEvent,
  ArtifactArchivedEvent,
} from "./artifact-registry/index.js";
